# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MWNN.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MWNN.proto',
  package='MWNN',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\nMWNN.proto\x12\x04MWNN\"S\n\x0fMWNNTensorProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0c\n\x04\x64ims\x18\x03 \x03(\x05\x12\x16\n\nfloat_data\x18\x04 \x03(\x02\x42\x02\x10\x01\"k\n\x12MWNNAttributeProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x10\n\x08int_data\x18\x03 \x03(\x05\x12\x12\n\nfloat_data\x18\x04 \x03(\x02\x12\x13\n\x0bstring_data\x18\x05 \x03(\t\"}\n\rMWNNNodeProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07op_type\x18\x02 \x01(\t\x12\x0f\n\x07ip_name\x18\x03 \x03(\t\x12\x0f\n\x07op_name\x18\x04 \x03(\t\x12+\n\tattribute\x18\x05 \x03(\x0b\x32\x18.MWNN.MWNNAttributeProto\"\xdc\x01\n\x0eMWNNGraphProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07ip_name\x18\x02 \x03(\t\x12\x0f\n\x07op_name\x18\x03 \x03(\t\x12!\n\x04node\x18\x04 \x03(\x0b\x32\x13.MWNN.MWNNNodeProto\x12*\n\x0binitializer\x18\x05 \x03(\x0b\x32\x15.MWNN.MWNNTensorProto\x12$\n\x05input\x18\x06 \x03(\x0b\x32\x15.MWNN.MWNNTensorProto\x12%\n\x06output\x18\x07 \x03(\x0b\x32\x15.MWNN.MWNNTensorProto'
)




_MWNNTENSORPROTO = _descriptor.Descriptor(
  name='MWNNTensorProto',
  full_name='MWNN.MWNNTensorProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MWNN.MWNNTensorProto.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='MWNN.MWNNTensorProto.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dims', full_name='MWNN.MWNNTensorProto.dims', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_data', full_name='MWNN.MWNNTensorProto.float_data', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=103,
)


_MWNNATTRIBUTEPROTO = _descriptor.Descriptor(
  name='MWNNAttributeProto',
  full_name='MWNN.MWNNAttributeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MWNN.MWNNAttributeProto.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='MWNN.MWNNAttributeProto.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_data', full_name='MWNN.MWNNAttributeProto.int_data', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_data', full_name='MWNN.MWNNAttributeProto.float_data', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_data', full_name='MWNN.MWNNAttributeProto.string_data', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=212,
)


_MWNNNODEPROTO = _descriptor.Descriptor(
  name='MWNNNodeProto',
  full_name='MWNN.MWNNNodeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MWNN.MWNNNodeProto.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_type', full_name='MWNN.MWNNNodeProto.op_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_name', full_name='MWNN.MWNNNodeProto.ip_name', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_name', full_name='MWNN.MWNNNodeProto.op_name', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='MWNN.MWNNNodeProto.attribute', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=339,
)


_MWNNGRAPHPROTO = _descriptor.Descriptor(
  name='MWNNGraphProto',
  full_name='MWNN.MWNNGraphProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MWNN.MWNNGraphProto.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_name', full_name='MWNN.MWNNGraphProto.ip_name', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_name', full_name='MWNN.MWNNGraphProto.op_name', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node', full_name='MWNN.MWNNGraphProto.node', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initializer', full_name='MWNN.MWNNGraphProto.initializer', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input', full_name='MWNN.MWNNGraphProto.input', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output', full_name='MWNN.MWNNGraphProto.output', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=562,
)

_MWNNNODEPROTO.fields_by_name['attribute'].message_type = _MWNNATTRIBUTEPROTO
_MWNNGRAPHPROTO.fields_by_name['node'].message_type = _MWNNNODEPROTO
_MWNNGRAPHPROTO.fields_by_name['initializer'].message_type = _MWNNTENSORPROTO
_MWNNGRAPHPROTO.fields_by_name['input'].message_type = _MWNNTENSORPROTO
_MWNNGRAPHPROTO.fields_by_name['output'].message_type = _MWNNTENSORPROTO
DESCRIPTOR.message_types_by_name['MWNNTensorProto'] = _MWNNTENSORPROTO
DESCRIPTOR.message_types_by_name['MWNNAttributeProto'] = _MWNNATTRIBUTEPROTO
DESCRIPTOR.message_types_by_name['MWNNNodeProto'] = _MWNNNODEPROTO
DESCRIPTOR.message_types_by_name['MWNNGraphProto'] = _MWNNGRAPHPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MWNNTensorProto = _reflection.GeneratedProtocolMessageType('MWNNTensorProto', (_message.Message,), {
  'DESCRIPTOR' : _MWNNTENSORPROTO,
  '__module__' : 'MWNN_pb2'
  # @@protoc_insertion_point(class_scope:MWNN.MWNNTensorProto)
  })
_sym_db.RegisterMessage(MWNNTensorProto)

MWNNAttributeProto = _reflection.GeneratedProtocolMessageType('MWNNAttributeProto', (_message.Message,), {
  'DESCRIPTOR' : _MWNNATTRIBUTEPROTO,
  '__module__' : 'MWNN_pb2'
  # @@protoc_insertion_point(class_scope:MWNN.MWNNAttributeProto)
  })
_sym_db.RegisterMessage(MWNNAttributeProto)

MWNNNodeProto = _reflection.GeneratedProtocolMessageType('MWNNNodeProto', (_message.Message,), {
  'DESCRIPTOR' : _MWNNNODEPROTO,
  '__module__' : 'MWNN_pb2'
  # @@protoc_insertion_point(class_scope:MWNN.MWNNNodeProto)
  })
_sym_db.RegisterMessage(MWNNNodeProto)

MWNNGraphProto = _reflection.GeneratedProtocolMessageType('MWNNGraphProto', (_message.Message,), {
  'DESCRIPTOR' : _MWNNGRAPHPROTO,
  '__module__' : 'MWNN_pb2'
  # @@protoc_insertion_point(class_scope:MWNN.MWNNGraphProto)
  })
_sym_db.RegisterMessage(MWNNGraphProto)


_MWNNTENSORPROTO.fields_by_name['float_data']._options = None
# @@protoc_insertion_point(module_scope)
