package(
    default_visibility = [
        "//visibility:public",
    ],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "metawarenn_kernels_ref",
    srcs = [
    ],
    hdrs = [
        "mli_math.h",
    ],
    tags = [
        "manual",
        "nobuilder",
    ],
)
