package(
    default_visibility = [
        "//visibility:public",
    ],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "metawarenn_optimizer",
    srcs = [
        "metawarenn_optimizer.cc",
        "dummy_pass_1.cc",
        "dummy_pass_2.cc",
        "dummy_pass_3.cc",
        "pass_manager.cc",
    ],
    hdrs = [
        "metawarenn_optimizer.h",
        "dummy_pass_1.h",
        "dummy_pass_2.h",
        "dummy_pass_3.h",
        "pass_manager.h",
    ],
    tags = [
        "manual",
        "nobuilder",
    ],
)
