package(
    default_visibility = [
        "//visibility:public",
    ],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "metawarenn_kernels_api",
    srcs = [
    ],
    hdrs = [
        "mli_helpers_api.h",
        "mli_kernels_api.h",
        "mli_krn_avepool_spec_api.h",
        "mli_krn_conv2d_spec_api.h",
        "mli_krn_depthwise_conv2d_spec_api.h",
        "mli_krn_maxpool_spec_api.h",
        "mli_mov_api.h",
    ],
    tags = [
        "manual",
        "nobuilder",
    ],
)
